[package]
org = "admin"
name = "agent_chat"
version = "0.1.0"
distribution = "2201.12.0-20250228-201300-8d411a0f"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "ai.agent"
version = "0.7.11"
repository = "local"
